spring.application.name=apirecreation
server.port=8081

# ==========================================
# DATASOURCE CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/ane_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# Silenciar advertencias internas del framework
logging.level.org.hibernate=ERROR
logging.level.org.springframework.web=INFO
